USE DATABASE TAXI_ANALYTICS;
USE SCHEMA GOLD;


COPY INTO DAILY_TRIP_SUMMARY
FROM @gold_stage/daily_trip_summary/
FILE_FORMAT = (
    TYPE = PARQUET
)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;


COPY INTO HOURLY_DEMAND
FROM @gold_stage/hourly_demand/
FILE_FORMAT = (
    TYPE = PARQUET
)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;


COPY INTO LOCATION_METRICS
FROM @gold_stage/location_metrics/
FILE_FORMAT = (
    TYPE = PARQUET
)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;