USE DATABASE TAXI_ANALYTICS;
USE SCHEMA GOLD;


COPY INTO DAILY_TRIP_SUMMARY
FROM @GOLD_STAGE/daily_trip_summary/
FILE_FORMAT = (
    TYPE = PARQUET
)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;


COPY INTO HOURLY_DEMAND
FROM @GOLD_STAGE/hourly_demand/
FILE_FORMAT = (
    TYPE = PARQUET
)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;


COPY INTO LOCATION_METRICS
FROM @GOLD_STAGE/location_metrics/
FILE_FORMAT = (
    TYPE = PARQUET
)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;